#  {.doc .doc-index}

## ImageryClient

Main functions for downloading imagery and segmentation data.

| | |
| --- | --- |
| [imagery.bounds_from_center](imagery.bounds_from_center.qmd#imageryclient.imagery.bounds_from_center) | Generate bounds from a center point and dimensions for each direction |
| [imagery.ImageryClient](imagery.ImageryClient.qmd#imageryclient.imagery.ImageryClient) | Tool to help download imagery and segmentation data. |

## Compositing

Functions for generating overlay visualizations of images and segmentation.

| | |
| --- | --- |
| [composite.stack_images](composite.stack_images.qmd#imageryclient.composite.stack_images) | Stack an iterable of images either veritcally or horizontally |
| [composite.composite_overlay](composite.composite_overlay.qmd#imageryclient.composite.composite_overlay) | Make a colored composite overlay for a 3d mask from an iterable of masks. |

## Utilities

Additional utility functions for working with imagery and segmentation data.

| | |
| --- | --- |
| [utils.rescale_to_bounds](utils.rescale_to_bounds.qmd#imageryclient.utils.rescale_to_bounds) |  |
| [utils.binary_seg_outline](utils.binary_seg_outline.qmd#imageryclient.utils.binary_seg_outline) | Convert a 2d image segmentation to a binary outline inside or outside the segmentation |
| [utils.mask_image](utils.mask_image.qmd#imageryclient.utils.mask_image) | Apply mask as a a transparency layer to seg |
| [utils.segmentation_masks](utils.segmentation_masks.qmd#imageryclient.utils.segmentation_masks) | Convert a segmentation array into a dict of binary masks for each root id. |