# composite.discrete_colors { #imageryclient.composite.discrete_colors }

`composite.discrete_colors(segs, palette=DEFAULT_PALETTE, h=DEFAULT_H, l=DEFAULT_L, s=DEFAULT_S)`

Generate discrete colors for segmentations from a palette
generator. Defaults to perceptually uniform differences with
high saturation.

## Parameters

| Name      | Type                  | Description                                                                                                     | Default           |
|-----------|-----------------------|-----------------------------------------------------------------------------------------------------------------|-------------------|
| `segs`    | list or dict          | Dict or list of segmentations to provide colors for.                                                            | _required_        |
| `palette` | 'husl', 'hls', or str | Which palette system to use, by default 'husl'. Will accept anything allowed by seaborn color_palette function. | `DEFAULT_PALETTE` |
| `h`       | float                 | Hue value if husl or hls palettes are used, by default 0.01                                                     | `DEFAULT_H`       |
| `l`       | float                 | Lightness if husl or hls palettes are used, by default 0.6                                                      | `DEFAULT_L`       |
| `s`       | int                   | Saturation if husl or hls palettes are used, by default 1                                                       | `DEFAULT_S`       |

## Returns

| Type         | Description                                   |
|--------------|-----------------------------------------------|
| List or dict | List or dict with one color per segmentation. |