# composite.composite_overlay { #imageryclient.composite.composite_overlay }

`composite.composite_overlay(segs, colors=None, alpha=0.2, imagery=None, outline=False, merge_outline=True, overlap=True, width=10, side='out', dim=2, palette=DEFAULT_PALETTE, h=DEFAULT_H, l=DEFAULT_L, s=DEFAULT_S)`

Make a colored composite overlay for a 3d mask from an iterable of masks.

## Parameters

| Name            | Type                                  | Description                                                                                                                                                                        | Default    |
|-----------------|---------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| `segs`          |                                       | Iterable of masked images of the same size. If a dict, colors must be a dict as well.                                                                                              | _required_ |
| `colors`        | list-like, dict, or None              | Iterable of RGB colors of the same size as masks. If a dict, masks must also be a dict and colors must have all keys in masks. If None, uses `discrete_colors` to generate colors. | `None`     |
| `alpha`         | float                                 | Alpha value for the overlay                                                                                                                                                        | `0.2`      |
| `imagery`       | PIL.PIL.Image.PIL.Image.Image or None | If an Image, applies the overlay to the image, by default None                                                                                                                     | `None`     |
| `outline`       | bool                                  | If True, produces an outline instead of a flat overay, by default False                                                                                                            | `False`    |
| `merge_outline` | bool                                  | If True, the merge outline applies to the segmentation as a whole and thus internal contacts are not outlined.                                                                     | `True`     |
| `overlap`       | bool                                  | If False, segmentations later in the list will not overlap segmentations earlier on the list.                                                                                      | `True`     |
| `width`         | int                                   | If outline=True, sets the width of the outline, by default 10                                                                                                                      | `10`       |
| `side`          | out or 'in'                           | If outline=True, selects if the outline is inside or outside the original segmentation mask, by default 'out'                                                                      | `'out'`    |
| `dim`           | int                                   | Determines axis over which slices are iterated if the data is 3 dimensional. Default is 2 (z-axis).                                                                                | `2`        |

## Returns

| Type                                  | Description                                                                                                                                                                     |
|---------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| list or PIL.PIL.Image.PIL.Image.Image | Image or list of composite overlay images, optionally overlaid over provided imagery. List or single image is determined based on segmentation arrays being 2 or 3 dimensional. |